gazebo_ros_control:
  pid_gains:
    wheel_left_joint:
      p: 0.015
      i: 1.0
      d: 0.0
      antiwindup: true
      i_clamp_max: 0.1
      i_clamp_min: -0.1
    wheel_right_joint:
      p: 0.015
      i: 1.0
      d: 0.0
      antiwindup: true
      i_clamp_max: 0.1
      i_clamp_min: -0.1